<?php

namespace App\Console\Commands\Development;

use App\Exceptions\HttpException\EmptyException;
use App\Services\ApiKeyService;
use App\Services\BankService;
use App\Services\PartnerService;
use Illuminate\Console\Command;

class GeneratePartnerAPIKey extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'generate:partner_api_keys {partner_id} {key_name} {key_description}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate Bank API Keys';

    private $partnerService;

    private $apiKeyService;
    /**
     * @var ApiKeyService
     */

    /**
     * Create a new command instance.
     *
     * @return void
     *
     * @param BankService $bankService
     */
    public function __construct(
        PartnerService $partnerService,
        ApiKeyService $apiKeyService)
    {
        parent::__construct();
        $this->apiKeyService = $apiKeyService;
        $this->partnerService = $partnerService;
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $is_test = true;

        $partnerId = $this->argument('partner_id');
        $generatedText = 'Generated by command';
        $keyName = $this->argument('key_name') ?? $generatedText;
        $keyDescription = $this->argument('key_description') ?? $generatedText;

        $partner = $this->partnerService->getPartnerById($partnerId);

        throw_if(empty($partner), new EmptyException('partner not found'));

        $randomIv = $this->apiKeyService->generateRandomIV();

        $secret = $this->apiKeyService->generateSecret(false);

        $apiKey = $this->apiKeyService->generateKeyByPartner(
            $partner,
            $secret,
            $randomIv,
            $keyName,
            $keyDescription
        );

        $apiKey->secret = $secret.$randomIv;
        $apiKey->is_first_generate = true;

        $this->info("Generate partner api_keys secret: $apiKey->secret");
    }
}
