<?php

namespace App\Console\Commands\Development;

use App\Services\ApiKeyService;
use Illuminate\Console\Command;

class GenerateAdminAPIKey extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'generate:admin_api_keys {--is_test}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate Admin API Keys';
    /**
     * @var ApiKeyService
     */
    private $apiKeyService;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct(ApiKeyService $apiKeyService)
    {
        parent::__construct();
        $this->apiKeyService = $apiKeyService;
    }

    /**
     * Execute the console command.
     *
     * @throws \App\Exceptions\TokenPrefixException
     */
    public function handle()
    {
        $is_test = $this->option('is_test');

        $generated_text = 'Generated by command';

        $random_iv = $this->apiKeyService->generateRandomIV();

        $secret = $this->apiKeyService->generateSecret($is_test);

        $this->apiKeyService->generateKeyByAdmin(
            $secret,
            $random_iv,
            $is_test,
            $generated_text,
            $generated_text
        );

        $admin_api_key = $secret.$random_iv;

        $this->info("Generate admin api_keys secret: $admin_api_key");
    }
}
