<?php

namespace App\Console\Commands\Development;

use App\Exceptions\HttpException\EmptyException;
use App\Http\Resources\Platform\ApiKeyResource;
use App\Services\ApiKeyService;
use App\Services\BankService;
use Illuminate\Console\Command;

class GenerateBankAPIKey extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'generate:bank_api_keys {bank_id}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate Bank API Keys';
    /**
     * @var ApiKeyService
     */
    private $apiKeyService;
    /**
     * @var BankService
     */
    private $bankService;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct(
        BankService $bankService,
        ApiKeyService $apiKeyService)
    {
        parent::__construct();
        $this->apiKeyService = $apiKeyService;
        $this->bankService = $bankService;
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $is_test = true;

        $bank_id = $this->argument('bank_id');

        $generated_text = 'Generated by command';

        $bank = $this->bankService->getBankById($bank_id);

        throw_if(empty($bank), new EmptyException('bank not found'));

        $random_iv = $this->apiKeyService->generateRandomIV();

        $secret = $this->apiKeyService->generateSecret($is_test);

        $api_key = $this->apiKeyService->generateKeyByBank(
            $bank,
            $secret,
            $random_iv,
            $is_test,
            $generated_text,
            $generated_text
        );

        $api_key->secret = $secret.$random_iv;
        $api_key->is_first_generate = true;
//        $result = new ApiKeyResource($api_key);

        $this->info("Generate bank api_keys secret: $api_key->secret");
    }
}
